# Definisci prima il System
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: authentication-system
  title: Authentication System
  description: |
    Collection of authentication and authorization components.
    This system includes guards, middlewares, and utilities for handling authentication in our applications.
  tags:
    - authentication
    - security
spec:
  owner: guests

---
# Poi il tuo Component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nestjs-bearer-guard
  title: NestJS Bearer Token Guard
  description: |
    Factory pattern for Bearer token authentication in NestJS.
    
    ## Usage Example:
    ```typescript
    // At Controller level
    @UseGuards(createBearerAuthGuard('key_path_in_configService'))
    @Get('protected')
    async getProtectedResource() {
      return { message: 'Authorized!' };
    }
    ```
  links:
    - url: https://github.com/danisg96/nest-bearer-token-guard-factory/blob/main/factories/BearerToken.factory.ts
      title: Factory Source Code
      icon: github
    - url: https://github.com/danisg96/nest-bearer-token-guard-factory/blob/main/guards/BearerToken.guard.ts
      title: Guard Source Code
      icon: github
    - url: https://github.com/danisg96/nest-bearer-token-guard-factory/blob/main/README.md
      title: Full Documentation
      icon: docs
  tags:
    - nestjs
    - authentication
    - bearer-token
    - guards
    - typescript
  annotations:
    github.com/project-slug: danisg96/nest-bearer-token-guard-factory
    backstage.io/techdocs-ref: dir:.
    demo.backstage.io/techdocs-builder: local
spec:
  type: library
  lifecycle: production
  owner: guests
  system: authentication-system  # Ora il system esiste!