apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nestjs-bearer-guard
  title: NestJS Bearer Token Guard
  description: |
    Factory pattern for Bearer token authentication in NestJS.
    
    ## Usage Example:
    ```typescript
    // At Controller level
    @UseGuards(createBearerAuthGuard('key_path_in_configService'))
    @Get('protected')
    async getProtectedResource() {
      return { message: 'Authorized!' };
    }
    ```
  links:
    - url: https://github.com/danisg96/nest-bearer-token-guard-factory/blob/main/factories/BearerToken.factory.ts
      title: Factory Source Code
      icon: github
    - url: https://github.com/danisg96/nest-bearer-token-guard-factory/blob/main/guards/BearerToken.guard.ts
      title: Guard Source Code
      icon: github
    - url: https://github.com/danisg96/nest-bearer-token-guard-factory/blob/main/README.md
      title: Full Documentation
      icon: docs
  tags:
    - nestjs
    - authentication
    - bearer-token
    - guards
    - typescript
  annotations:
    # Link diretto al file principale
    github.com/project-slug: danisg96/nest-bearer-token-guard-factory
    backstage.io/source-location: url:https://github.com/danisg96/nest-bearer-token-guard-factory
    # Puoi aggiungere link alla documentazione
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: production
  owner: guests  # o il tuo username
  system: authentication-system  # opzionale, per raggruppare componenti